# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin code style:
kotlin.code.style=official
android.newDsl=false
android.disallowKotlinSourceSets=false

# Aggressive workarounds for missing jlink (JRE vs JDK issue)
android.jdkImageTransform.enabled=false
android.useFullClasspathForDexingTransform=true

# Force Gradle to look for a full JDK for compilation tasks.
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=false
org.gradle.java.home=/Users/enisogdum/.gradle/jdks/eclipse_adoptium-21-aarch64-os_x.2/jdk-21.0.7+6/Contents/Home

